### ISSUE TITLE
Contributers

### ISSUE THREAD

**Issue by griffins** [tawn33y/EasySQL#3]
Kindly add a few contributers

**Comment by tawn33y** [comment]
Hi @griffins @SmoDav @nyandikadon,
Sorry, it's been a while since I wrote this library. Let me know if you'd like to be added as contributors and carry on the development. Cheers!

**Comment by tawn33y** [comment]
Hi @griffins @SmoDav @nyandikadon,
Kindly let me know if you'd like to be added as contributors. Cheers!
